channels:
  - conda-forge
dependencies:
  - anaconda-project
  - autopep8
  - black
  - boa
  - cmake
  - conda-build-all
  - conda-export
  - conda-forge-ci-setup
  - conda-smithy
  - conda-tree
  - conda-verify
  - constructor
  - cookiecutter
  - decorator
  - flake8
  - gcc
  - gh
  - gradle
  - grayskull
  - isort
  - make
  - maven
  - mypy
  - ncdu
  - pandas
  - pip-tools
  - pipreqs
  - pre-commit
  - pre-commit-hooks
  - pyparsing
  - python-graphviz
  - regex
  - sbt
  - sphinx
  - sqlite
  - su-exec
  - tini
  - tox-conda
  - yarn
